[package]
authors = ["tamasfe"]
categories = ["development-tools", "command-line-utilities"]
description = "A CLI for Taplo TOML toolkit"
edition = "2021"
homepage = "https://taplo.tamasfe.dev"
keywords = ["toml", "linter", "formatter"]
license = "MIT"
name = "taplo-cli"
repository = "https://github.com/tamasfe/taplo"
version = "0.9.1"

[features]
default = ["rustls-tls"]
lsp = ["taplo-lsp", "async-ctrlc"]
native-tls = ["taplo-common/native-tls"]
rustls-tls = ["taplo-common/rustls-tls"]
toml-test = []

[dependencies]
anyhow = { workspace = true, features = ["backtrace"] }
async-ctrlc = { version = "1.2.0", features = ["stream"], optional = true }
clap = { version = "3.0.0", features = ["derive", "cargo", "env"] }
codespan-reporting = "0.11.1"
futures = { workspace = true }
glob = { workspace = true }
hex = { workspace = true }
itertools = { workspace = true }
once_cell = { workspace = true }
regex = { workspace = true }
reqwest = { version = "0.11.9", default-features = false, features = ["json"] }
schemars = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
taplo = { version = "0.13.1", path = "../taplo", features = ["serde"] }
taplo-common = { version = "0.5.1", path = "../taplo-common" }
taplo-lsp = { version = "0.7.1", path = "../taplo-lsp", default-features = false, optional = true }
time = { workspace = true, features = ["parsing"] }
toml = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
url = { workspace = true }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
# `prettydiff` is also a CLI that pulls in `clap` by default
ansi_term = "0.12"
atty = "0.2.14"
lsp-async-stub = { version = "0.6.0", path = "../lsp-async-stub", features = [
  "tokio-tcp",
  "tokio-stdio",
] }
prettydiff = { version = "0.6.1", default-features = false }
tokio = { version = "1.24.2", features = [
  "sync",
  "fs",
  "time",
  "io-std",
  "rt-multi-thread",
  "parking_lot",
], default-features = false }

[target.'cfg(target_arch = "wasm32")'.dependencies]
tokio = { version = "1.24.2", features = [
  "sync",
  "parking_lot",
  "io-util",
], default-features = false }

[package.metadata.auto-tag]
enabled = true

[[bin]]
name = "taplo"
path = "bin/taplo.rs"
