[package]
authors = ["tamasf97 <tamasf97@outlook.com>"]
description = "Language server for Taplo"
edition = "2021"
homepage = "https://taplo.tamasfe.dev"
license = "MIT"
name = "taplo-lsp"
repository = "https://github.com/tamasfe/taplo"
version = "0.7.1"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["rustls-tls"]
native-tls = ["taplo-common/native-tls"]
rustls-tls = ["taplo-common/rustls-tls"]

[dependencies]
anyhow = { workspace = true }
arc-swap = { workspace = true }
either = { workspace = true }
figment = { version = "0.10.6", features = ["json"] }
futures = { workspace = true }
indexmap = { version = "1.6", features = ["serde"] }
itertools = { workspace = true }
lsp-async-stub = { version = "0.6.3", path = "../lsp-async-stub" }
lsp-types = { version = "0.93.0", features = ["proposed"] }
once_cell = { workspace = true }
parking_lot = { workspace = true }
regex = { workspace = true }
reqwest = { version = "0.11.9", default-features = false, features = ["json"] }
schemars = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true, features = ["preserve_order"] }
tap = { workspace = true }
taplo = { version = "0.13.1", path = "../taplo", features = ["serde"] }
taplo-common = { version = "0.5.1", path = "../taplo-common" }
time = { version = "0.3", features = ["formatting", "parsing"] }
toml = { workspace = true }
tracing = { workspace = true }

[package.metadata.auto-tag]
enabled = true
